# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveObjCStudyDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ReactiveObjC', '~> 2.1.2'
  # Pods for ReactiveObjCStudyDemo

  target 'ReactiveObjCStudyDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactiveObjCStudyDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
